openapi: 3.0.3
info:
  title: A Força Admin API
  description: A **Força** é uma organização que busca ajudar os trabalhadores autônomos da cidade de Lavras (MG) e região a encontrar e firmar contrato com pessoas interessadas em seus serviços.
  version: 1.0.0
tags:
  - name: categoria
  - name: servico
paths:
  /categoria:
    post:
      tags:
        - categoria
      summary: Cria nova categoria
      operationId: criarCategoria
      requestBody:
        description: Deve ser informado apenas o nome da categoria, logo, o nome é obrigatório. Além disso, deve ser único e não ultrapassar 50 caracteres.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: TI
      responses:
        "201":
          description: Nova categoria criada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        "400":
          description: |-
            - O nome da categoria é obrigatório
            - O nome da categoria deve ter no máximo 50 caracteres
            - Nome da categoria já registrado
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome da categoria é obrigatório
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome da categoria deve ter no máximo 50 caracteres
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: Nome da categoria já registrado
    get:
      tags:
        - categoria
      summary: Obtém todas as categorias
      operationId: obterTodasCategorias
      responses:
        "200":
          description: Todas as categorias registradas. Senão apenas um vetor vazio.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Categoria"
  /categoria/{id}:
    get:
      tags:
        - categoria
      summary: Obtém categoria pelo ID
      operationId: obterCategoriaPorId
      parameters:
        - name: id
          in: path
          description: ID da categoria buscada
          required: true
          schema:
            type: number
            example: 10
      responses:
        "200":
          description: Categoria encontrada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        "404":
          description: Categoria não encontrada
          content:
            text/plain:
              schema:
                $ref: "#/components/responses/RegistroNaoEncontrado"
    put:
      tags:
        - categoria
      summary: Atualiza atributos da categoria
      operationId: atualizaCategoriaPorId
      parameters:
        - name: id
          in: path
          description: ID da categoria atualizada
          required: true
          schema:
            type: number
            example: 10
      requestBody:
        description: Deve ser informado apenas o nome da categoria
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "IT"
      responses:
        "200":
          description: Categoria encontrada e atualizada
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 10
                  nome:
                    type: string
                    example: "IT"
        "400":
          description: |-
            - O nome da categoria é obrigatório
            - O nome da categoria deve ter no máximo 50 caracteres
            - Nome da categoria já registrado
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome da categoria é obrigatório
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome da categoria deve ter no máximo 50 caracteres
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: Nome da categoria já registrado
        "404":
          description: Categoria não encontrada
          content:
            text/plain:
              schema:
                $ref: "#/components/responses/RegistroNaoEncontrado"
    delete:
      tags:
        - categoria
      summary: Remove categoria
      operationId: removeCategoriaPorId
      parameters:
        - name: id
          in: path
          description: ID da categoria removida
          required: true
          schema:
            type: number
            example: 1
      responses:
        "204":
          description: Categoria encontrada e deletada
        "404":
          description: Categoria não encontrada
          content:
            text/plain:
              schema:
                $ref: "#/components/responses/RegistroNaoEncontrado"
        "409":
          description: Categoria vinculada a algum registro
          content:
            application/json:
              schema:
                properties:
                  mensagem:
                    type: string
                    example: Essa categoria está sendo utilizada em outros registros
  /servico:
    post:
      tags:
        - servico
      summary: Cria novo serviço
      operationId: criaServico
      requestBody:
        description: Deve ser informado o nome do serviço e o ID da categoria já registrada na base de dados, ambos obrigatórios. O nome do serviço deve ser único e não ultrapassar 75 caracteres.
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: Manutenção de notebook
                categoriaId:
                  type: number
                  example: 10
      responses:
        "201":
          description: Novo serviço criado com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Servico"
        "400":
          description: |-
            - O nome do serviço é obrigatório
            - O nome do serviço deve ter no máximo 75 caracteres
            - A categoria é obrigatória e deve estar registrada
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome do serviço é obrigatório
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome do serviço deve ter no máximo 75 caracteres
                  - type: object
                    properties:
                      categoriaId:
                        type: string
                        example: A categoria é obrigatória e deve estar registrada
  /servico/{id}:
    get:
      tags:
        - servico
      summary: Obtém serviço pelo ID
      operationId: obterServicoPorId
      parameters:
        - name: id
          in: path
          description: ID do serviço buscado
          required: true
          schema:
            type: number
            example: 11
      responses:
        "200":
          description: Serviço encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Servico"
        "404":
          description: Serviço não encontrado
          content:
            text/plain:
              schema:
                $ref: "#/components/responses/RegistroNaoEncontrado"
    put:
      tags:
        - servico
      summary: Atualiza atributos do serviço registrado
      operationId: atualizaServicoPorId
      parameters:
        - name: id
          in: path
          description: ID do serviço atualizada
          required: true
          schema:
            type: number
            example: 11
      requestBody:
        description: Deve ser informado o nome do serviço e o ID da categoria.
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: Manutenção em computadores
                categoriaId:
                  type: number
                  example: 10
      responses:
        "200":
          description: Serviço encontrado e atualizado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    example: 11
                  nome:
                    type: string
                    example: Manutenção em computadores
                  categoria:
                    type: object
                    $ref: "#/components/schemas/Categoria"
        "400":
          description: |-
            - O nome do serviço é obrigatório
            - O nome do serviço deve ter no máximo 75 caracteres
            - A categoria é obrigatória e deve estar registrada
          content:
            application/json:
              schema:
                anyOf:
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome do serviço é obrigatório
                  - type: object
                    properties:
                      nome:
                        type: string
                        example: O nome do serviço deve ter no máximo 75 caracteres
                  - type: object
                    properties:
                      categoriaId:
                        type: string
                        example: A categoria é obrigatória e deve estar registrada
        "404":
          description: Serviço não encontrada
          content:
            text/plain:
              schema:
                $ref: "#/components/responses/RegistroNaoEncontrado"
components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: number
          example: 10
        nome:
          type: string
          example: TI
    Servico:
      type: object
      properties:
        id:
          type: number
          example: 11
        nome:
          type: string
          example: Manutenção de notebook
        categoria:
          $ref: "#/components/schemas/Categoria"
  responses:
    "RegistroNaoEncontrado":
      type: string
      example: Registro não encontrado
